#!/bin/bash
set -ueo pipefail

# Source config script
. scripts/config_ACL2013_LDC2013E117.sh

# Extract and preprocess data
if [ ! -f "$JAMR_HOME/data/LDC2013E117.tgz" ]; then
    echo 'Error: Please copy LDC2013E117.tgz to the directory $JAMR_HOME/data before running this script.'
    exit 1
fi
mkdir -p "$JAMR_HOME/data"
pushd "$JAMR_HOME/data"
tar -xzf LDC2013E117.tgz
popd

pushd "$JAMR_HOME/scripts/preprocessing"
patch "${DATA_DIR}/deft-amr-release-r3-proxy.txt" deft-amr-release-r3-proxy.txt.patch
LDC2013E117/make_splits.sh
./PREPROCESS.sh
popd

# Train
pushd "$JAMR_HOME/scripts/training"
./cmd.conceptTable.train
echo "Training stage 1"
./cmd.stage1-weights
echo "Training stage 2"
./cmd.stage2-weights

# Evaluate on test set
echo "  *** Test Evaluation (gold concept ID) ***"
./cmd.test.decode.stage2only
${JAMR_HOME}/scripts/smatch_v1_0/smatch_modified.py --pr -f ${JAMR_HOME}/experiments/current/test.decode.stage2only ${JAMR_HOME}/data/LDC-2013-Sep/amr-release-proxy.test
echo "  *** Test Evaluation (all stages) ***"
./cmd.test.decode.allstages
${JAMR_HOME}/scripts/smatch_v1_0/smatch_modified.py --pr -f ${JAMR_HOME}/experiments/current/test.decode.allstages ${JAMR_HOME}/data/LDC-2013-Sep/amr-release-proxy.test

