#!/bin/bash

#fsc -classpath "../wordnet/edu.mit.jwi_2.3.0_jdk.jar" *.scala
fsc -classpath "../wordnet/edu.mit.jwi_2.3.0_jdk.jar" *.scala GraphDecoder/*.scala
#fsc -classpath "../wordnet/edu.mit.jwi_2.3.0_jdk.jar" -optimize -Yinline-warnings *.scala GraphDecoder/*.scala
